# Generated by Django 3.1.2 on 2020-11-22 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_date_time', models.DateTimeField()),
                ('event_description', models.TextField(max_length=200)),
                ('event_price', models.IntegerField()),
                ('event_fee', models.IntegerField()),
                ('event_maxteams', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury_name', models.CharField(max_length=20)),
                ('jury_email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fest_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fest_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=20)),
                ('stud_email', models.EmailField(max_length=254)),
                ('stud_college', models.CharField(max_length=50)),
                ('stud_USN', models.CharField(max_length=10)),
                ('stud_part_events', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fest_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_USN', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vol_event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fest_app.event')),
            ],
        ),
        migrations.DeleteModel(
            name='roles',
        ),
        migrations.AddField(
            model_name='results',
            name='runner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='fest_app.student'),
        ),
        migrations.AddField(
            model_name='results',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='event_winner', to='fest_app.student'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fest_app.location'),
        ),
    ]
