# Generated by Django 3.1.2 on 2020-11-22 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fest_app', '0002_auto_20201122_0719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volunteers',
            new_name='Volunteer',
        ),
        migrations.AlterField(
            model_name='results',
            name='runner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='event_runner', to='fest_app.student'),
        ),
    ]
