# Generated by Django 3.1.2 on 2020-11-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0003_auto_20201122_0722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
    ]
