# Generated by Django 3.1.2 on 2020-10-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hari_Om', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='vol_id',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
