# Generated by Django 3.1.2 on 2020-11-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hari_Om', '0002_volunteers_vol_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_id', models.IntegerField()),
                ('br_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='volunteers',
            name='branch',
            field=models.ManyToManyField(to='Hari_Om.Branch'),
        ),
    ]
