# Generated by Django 3.1.2 on 2020-11-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hari_Om', '0003_auto_20201106_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='branch',
            field=models.ManyToManyField(blank=True, to='Hari_Om.Branch'),
        ),
    ]
